### PR TITLE
Add support for XHR handlers

### PR DESCRIPTION
**Pull request by MulverineX**
Current usecase: intercepting requests from Prisma to DB in order to easily implement native internal DB queries.

### CODE REVIEW

**Comment by MulverineX** [comment]
I'm deciding to make my own library based on this one instead, there's quite a lot more I want to do with this and it doesn't appear that this repo is being maintained

**Comment by MulverineX** [comment]
@abner reactions don't push notifications 😅. After waiting a week with no response I had kinda given up. If we'll be able to collaborate though that's better. I'd like to hop into a voice call at some point to discuss if that's possible.

**Comment by abner** [comment]
> @abner reactions don't push notifications 😅. After waiting a week with no response I had kinda given up. If we'll be able to collaborate though that's better. I'd like to hop into a voice call at some point to discuss if that's possible.
> 
> The library as-is doesn't really suit my needs, and imo is kind of unintuitive to use as a backend framework. My goal is to be able to have a setup kinda similar to React Native, where most app logic & functionality is controlled by a JavaScript thread. Unfortunately I've been running into issues left and right, since this library is somewhat unfinished and is designed more with simple lambdas in mind. The setTimeout & console.log implementations are broken, errors don't push to the debug console, context appears to not actually persist, etc.

Hi @MulverineX . Sorry by that. Yesterday I was asleep when I was looking into my mailbox and saw the PR.. I am getting myself recovered from cold and also my dedication to the library is just partial as in my current job I am not working with Flutter. So I usually check some requests (lately more the PR's, at the weekends)

Yeah, the focus of the library is not actually allow to drive all the interaction with the UI or drive the application flow. React Native, NativeScript. Using Flutter, maybe the [webf](https://github.com/openwebf/webf] would fit better your intention. I would recovery the changes from the PR diffs if we do not want to send the PR with the changes again.

**Comment by MulverineX** [comment]
@abner unfortunately WebF uses a webview which kinda goes against my goal; native UI rendering. While I could use a background webview, that's still quite a bit of bloat, and could cause optimization/battery/uptime issues on mobile platforms. I think I'll continue with my fork of your library then, thank you very much for your existing work.

**Comment by MulverineX** [comment]
@abner Quite alright, thank you for eventually getting back to me. I hope you continue in good health and that your current job goes well. Unfortunately WebF doesn't really fit my usecase as I'm trying to use Native UI rendering. Even if I used it as a background webview, in that capacity, it would still be a lot of bloat and could cause issues on mobile platforms with battery/optimization/uptime/etc, which is especially important because its a music app. 

I think I will continue with my fork of your libary, I very much appreciate the work that you've done here though, thank you.

**Comment by abner** [comment]
Ok. Good luck. 
Just to clarify, webf does not uses WebView. [The project](https://openwebf.com/) created a webrenderer using the Flutter Native view engine, using quickjs as the JavaScript engine. It transforms html in native flutter components and allows to pass your own flutter components to be incorporated in this webrenderer as they were "we components". It is beyond what I just want to do here too, but as you describe what you want to do, I think it was the closest alternative. 
https://github.com/abner/flutter_js/pull/136#issuecomment-1732047876

**Comment by MulverineX** [comment]
Thank you.
After taking a closer look it does appear to be quite a lot more efficient than anticipated. Unfortunately, it appears to be riddled with compatibility issues and generally there's a lot more prior art when working with something like Hermes.

**Comment by abner** [comment]
https://github.com/abner/flutter_js/pull/136#issuecomment-1732232003
But in hermes, I think you will have to came out with all this things as Xhr, Fetch and other other stuff. In React Native, these support are provided by the native part of React Native, either in Android/Java - https://github.com/facebook/react-native/blob/29f62a41b4127735cfadaf084fc0b1761ec34a8f/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java#L64 or the counterpart in Objective-C/iOS - So you would have to provide these for hermes in any integration with Flutter.
I am also curious, do you have some kind of binding to hermes in Flutter you are going to use or are you still planning to develop it. If you do have something related and if you can share.

**Comment by MulverineX** [comment]
Dang, I just keep striking out, lol. So either I port lots of stuff from ReactNative, or I use WebF... Using WebF and fixing it up where need be might be the better option actually. I'll give WebF a try soon.

**Comment by abner** [comment]
I am just trying to help you as I have exploring this area for a while. 
Good luck with the experiments!

**Comment by MulverineX** [comment]
Looks like as is it's not exactly ideal for my use case https://github.com/openwebf/rfc/pull/6

**Comment by MulverineX** [comment]
After sponsoring & collaborating with andycall there is now a new library, [mercuryjs](https://pub.dev/packages/mercuryjs) (https://github.com/openwebf/mercury)! 🚀🎉

**Pull request closed without merging**
